#!/usr/bin/bash
. ords-lib
DURATION=${1:-1M}
echo ords-protocols DURATION=$DURATION

echo Demonstrate characteristics of different Tomcat protocols

echo -n "$(date) HTTP APR/native connector:"
build_urls cache_off GET http proxy_none rest_manual 1110
siege_tps $DURATION

echo -n "$(date) HTTP Non blocking Java connector:"
build_urls cache_off GET http proxy_none rest_manual 1111
siege_tps $DURATION

echo -n "$(date) HTTP Blocking Java connector:"
build_urls cache_off GET http proxy_none rest_manual 1112
siege_tps $DURATION

echo -n "$(date) HTTPS APR/native connector (OpenSSL):"
build_urls cache_off GET https proxy_none rest_manual 1210
siege_tps $DURATION

echo -n "$(date) HTTPS Non blocking Java connector (JSSE):"
build_urls cache_off GET https proxy_none rest_manual 1211
siege_tps $DURATION

echo -n "$(date) HTTPS Blocking Java connector (JSSE):"
build_urls cache_off GET https proxy_none rest_manual 1212
siege_tps $DURATION

