#!/usr/bin/bash
. orp-lib
THREADS=${1:-4}

sudo sed -i 's/maxThreads="[0-9]\+"/maxThreads="'$THREADS'"/' /etc/tomcat/server.xml

#TODO Put in function to save duplicate code
sed -i 's/<entry key="jdbc.InitialLimit">[0-9]\+<\/entry>/<entry key="jdbc.InitialLimit">'$THREADS'<\/entry>/' /opt/oracle/ords/config/ords/defaults.xml
sed -i 's/<entry key="jdbc.MinLimit">[0-9]\+<\/entry>/<entry key="jdbc.MinLimit">'$THREADS'<\/entry>/' /opt/oracle/ords/config/ords/defaults.xml
sed -i 's/<entry key="jdbc.MaxLimit">[0-9]\+<\/entry>/<entry key="jdbc.MaxLimit">'$THREADS'<\/entry>/' /opt/oracle/ords/config/ords/defaults.xml



