#!/usr/bin/bash
. orp-lib
DURATION=${1:-1M}

echo orp-connections, DURATION=$DURATION
echo Demonstate difference between 1 and 255 siege connections...
echo "Compare the values for 'Transaction rate' and 'Response time'"
build_urls cache_off GET http proxy_none rest_manual
siege -c   1 -t $DURATION >/dev/null
siege -c 255 -t $DURATION >/dev/null