#!/usr/bin/bash
. orp-lib

#Default 30*10 seconds=5 minutes
DURATION=${1:-10S}
ITERATIONS=${2:-30}

kill_siege

echo orp-warmup ITERATIONS=$ITERATIONS DURATION $DURATION
echo Demonstrate transaction rate increasing as Tomcat warms up
echo Also some ongoing variation in transaction rate 
echo Restarting Tomcat...
sudo systemctl restart tomcat.service
echo Sleep 15 seconds to allow Tomcat to start
sleep 15
build_urls cache_off GET http proxy_none rest_manual
for (( i=1; i<=$ITERATIONS; i++ ))  
do
    echo -n "$(date) "
    siege -c 255 -t $DURATION 2>&1 | grep rate
done
