#!/usr/bin/bash
ITERATIONS=${1:-5}
DURATION=${2:-1M}
echo orp-versions ITERATIONS=$ITERATIONS DURATION=$DURATION

. orp-lib

for VERSION in 19.1 19.2
do 
   sudo systemctl stop tomcat.service
   #Redirect otherwise overwhelms output
   #Obviously change for troubleshooting :)
   echo About to install ORDS $VERSION
   sudo sh /vagrant/scripts/ords.sh $VERSION >/dev/null 2>&1 
   echo Installation Completed
   sudo systemctl start tomcat.service
   build_urls cache_off GET http proxy_none rest_auto
   echo "ORDS Version "$VERSION" Auto REST:"
   for (( i=1; i<=$ITERATIONS; i++ ))  
   do
      echo -n "$(date): "
      siege_tps $DURATION
   done
   build_urls cache_off GET http proxy_none rest_manual
   echo "ORDS Version "$VERSION" Manual REST:"
   for (( i=1; i<=$ITERATIONS; i++ ))  
   do
      echo -n "$(date): "
      siege_tps $DURATION
   done
done
