#!/usr/bin/bash
DURATION=${1:-1M}
RESTART_WAIT_SECONDS=${2:-10}
echo orp-threads DURATION=$DURATION RESTART_WAIT_SECONDS=$RESTART_WAIT_SECONDS
echo Demonstrate effect of Tomcat Threads on performance
echo ORS connection pool is set to value of maxthreads
echo Remember to reset maxthreads  to 4 after these tests
echo This will happen automatically if the test is allowed to complete
. orp-lib


for THREADCOUNT in 1 2 4 8 16 32 64 128
do
   set_threads $THREADCOUNT $RESTART_WAIT_SECONDS
   for LOOPY in {1..3}
   do
       echo -n "$(date) "
      siege_tps $DURATION
   done     
done

set_threads 4 $RESTART_WAIT_SECONDS