# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
var_box            = 'bento/oracle-7.6'
var_vm_name        = 'ora18c-ords191-reverseproxy'
var_mem_size       = 8192
var_cpus           = 4
var_non_rotational = 'on' # SSD


Vagrant.configure("2") do |config|
  config.vm.box = var_box

  #Apache Tomcat
  #Tomcat HTTP
  config.vm.network "forwarded_port", guest: 1110, host: 1110
  #Tomcat HTTPS
  config.vm.network "forwarded_port", guest: 1210, host: 1210

  #Apache HTTP Server
  #HTTP - No cache
  config.vm.network "forwarded_port", guest: 2110, host: 2110
  #HTTP - Cache GETs
  config.vm.network "forwarded_port", guest: 2120, host: 2120
  #HTTPS - No Cache
  config.vm.network "forwarded_port", guest: 2210, host: 2210
  #HTTPS - Cache GETs
  config.vm.network "forwarded_port", guest: 2220, host: 2220

  #Nginx
  config.vm.network "forwarded_port", guest: 3110, host: 3110
  config.vm.network "forwarded_port", guest: 3120, host: 3120 #Cache GETs
  config.vm.network "forwarded_port", guest: 3130, host: 3130 #Cache POSTs
  config.vm.network "forwarded_port", guest: 3210, host: 3210 #TLS
  config.vm.network "forwarded_port", guest: 3220, host: 3220 #TLS Cache GETs
  config.vm.network "forwarded_port", guest: 3230, host: 3230 #TLS Cache POSTs

  #Varnish + Hitch
  config.vm.network "forwarded_port", guest: 4110, host: 4110
  config.vm.network "forwarded_port", guest: 4120, host: 4120 #Cache GETs
  config.vm.network "forwarded_port", guest: 4130, host: 4130 #Cache POSTs
  config.vm.network "forwarded_port", guest: 4210, host: 4210 #TLS
  config.vm.network "forwarded_port", guest: 4220, host: 4220 #TLS Cache GETs
  config.vm.network "forwarded_port", guest: 4230, host: 4230 #TLS Cache POSTs

  config.vm.network "forwarded_port", guest: 5500, host: 5500

  #Don't set hostname here otherwise db installation will fail :(
  #config.vm.hostname = "ords-reverseproxy.localdomain"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = var_mem_size
    vb.cpus   = var_cpus
    vb.name   = var_vm_name    
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', var_non_rotational]
  end
  #General setup
  config.vm.provision "shell", path: "scripts/setup.sh"
  #Oracle Database
  config.vm.provision "shell", path: "scripts/database.sh"
  #Set Hostname after creating database
  config.vm.provision "shell", path: "scripts/hostname.sh"
  #Generate certificates etc for use by Tomcat & Reverse Proxies
  config.vm.provision "shell", path: "scripts/tls.sh"
  #Apache Tomcat
  config.vm.provision "shell", path: "scripts/tomcat.sh"
  #ORDS
  config.vm.provision "shell", path: "scripts/ords.sh"
  #Apache HTTP Server
  config.vm.provision "shell", path: "scripts/httpd.sh"
  #Nginx
  config.vm.provision "shell", path: "scripts/nginx.sh"
  #Varnish
  config.vm.provision "shell", path: "scripts/varnish.sh"
  #Hitch
  config.vm.provision "shell", path: "scripts/hitch.sh"
  #Siege
  config.vm.provision "shell", path: "scripts/siege.sh"
end