# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
var_box            = 'bento/oracle-7.6'
var_vm_name        = 'ora18c-ords191-reverseproxy'
var_mem_size       = 4096
var_cpus           = 2
var_non_rotational = 'on' # SSD


Vagrant.configure("2") do |config|
  config.vm.box = var_box

  config.vm.network "forwarded_port", guest: 1111, host: 1111
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  config.vm.hostname = "ords-reverseproxy.localdomain"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = var_mem_size
    vb.cpus   = var_cpus
    vb.name   = var_vm_name    
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', var_non_rotational]
  end

  config.vm.provision "shell", path: "scripts/setup.sh"
  config.vm.provision "shell", path: "scripts/database.sh"
  config.vm.provision "shell", path: "scripts/tls.sh"
  config.vm.provision "shell", path: "scripts/tomcat.sh"
  config.vm.provision "shell", path: "scripts/ords.sh"
end
